name: web
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            extra-substituters = https://nix.monade.li
            extra-trusted-public-keys = nix.monade.li:2Zgy59ai/edDBizXByHMqiGgaHlE04G6Nzuhx1RPFgo=
      - name: Build
        run: |
          web=$(nix -L build .#web --print-out-paths)
          cp -rL --no-preserve=mode,ownership,timestamps "$web" pages
      - uses: actions/upload-pages-artifact@v1
        with:
          path: pages
          retention-days: 1
  deploy:
    if: github.ref_name == 'main'
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v2
